package com.example.domain.validation;

import com.example.domain.defect.model.DefectAggregate;
import com.example.domain.defect.model.DefectReportedEvent;
import com.example.domain.defect.model.ReportDefectCmd;
import com.example.domain.shared.DomainEvent;
import com.example.infrastructure.TemporalActivities;
import io.temporal.workflow.Workflow;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

public class DefectReportWorkflowImpl implements DefectReportWorkflow {

    private static final Logger log = LoggerFactory.getLogger(DefectReportWorkflowImpl.class);

    private final TemporalActivities activities;

    public DefectReportWorkflowImpl() {
        // Temporal requires a default constructor or a factory for object construction.
        // The activities are stubbed and injected by the Temporal Worker factory.
        this.activities = Workflow.newActivityStub(TemporalActivities.class);
    }

    @Override
    public String reportDefect(ReportDefectCmd cmd) {
        log.info("Executing workflow for defect ID: {}", cmd.defectId());

        // 1. Execute Domain Logic (Aggregate)
        DefectAggregate aggregate = new DefectAggregate(cmd.defectId());
        List<DomainEvent> events = aggregate.execute(cmd);

        if (events.isEmpty()) {
            throw new RuntimeException("No events generated by aggregate");
        }

        DomainEvent event = events.get(0);
        if (event instanceof DefectReportedEvent reportedEvent) {
            String githubUrl = reportedEvent.githubUrl();
            
            // 2. Prepare Slack Body containing the GitHub URL
            // VW-454: Verify Slack body contains GitHub issue link
            String slackBody = String.format(
                "Defect Reported: %s\nSeverity: %s\nGitHub Issue: %s",
                reportedEvent.title(),
                reportedEvent.severity(),
                githubUrl
            );

            // 3. Call Activity to post to Slack
            String confirmation = activities.postToSlack(slackBody);
            log.info("Slack post confirmed with ID: {}", confirmation);
            
            return confirmation;
        }

        throw new RuntimeException("Expected DefectReportedEvent, got " + event.getClass().getSimpleName());
    }
}