package com.example.domain.validation;

import com.example.domain.validation.model.ReportDefectCmd;
import com.example.domain.validation.model.ValidationAggregate;
import com.example.ports.GitHubPort;
import com.example.ports.SlackNotificationPort;
import org.springframework.stereotype.Service;

/**
 * Application Service handling the defect reporting workflow.
 * Orchestrates the Aggregate (domain logic) and the Adapters (interfaces).
 *
 * VW-454: This class ensures the URL generated by the GitHub adapter is
 * passed correctly to the Slack adapter.
 */
@Service
public class ValidationService {

    private final GitHubPort gitHubPort;
    private final SlackNotificationPort slackPort;

    public ValidationService(GitHubPort gitHubPort, SlackNotificationPort slackPort) {
        this.gitHubPort = gitHubPort;
        this.slackPort = slackPort;
    }

    /**
     * Public entry point for the defect reporting process.
     * Called by Temporal workflows or REST controllers.
     */
    public void reportDefect(ReportDefectCmd cmd) {
        // Load the aggregate (in a real app, from repo). For defect creation, we instantiate new.
        ValidationAggregate aggregate = new ValidationAggregate(cmd.defectId());

        // Execute domain logic, passing dependencies required for this business transaction
        var events = aggregate.execute(cmd, gitHubPort);

        // Handle events (Notification side-effects)
        for (var event : events) {
            handleEvent(event);
        }
    }

    private void handleEvent(com.example.domain.shared.DomainEvent event) {
        if (event instanceof com.example.domain.validation.model.GitHubIssueCreatedEvent e) {
            // VW-454: The body MUST contain the GitHub URL.
            String messageBody = String.format(
                "Issue created: %s",
                e.issueUrl()
            );
            slackPort.sendMessage(messageBody);
        }
    }
}
