package com.example.steps;

import com.example.adapters.OkHttpGitHubClient;
import com.example.domain.defect.model.ReportDefectCmd;
import com.example.domain.defect.service.DefectReportWorkflow;
import com.fasterxml.jackson.databind.ObjectMapper;
import okhttp3.OkHttpClient;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * TDD Red Phase Test for S-FB-1.
 * 
 * Validates that when a defect is reported, the Slack notification body
 * contains the GitHub issue URL.
 */
class DefectReportSteps {

    @Test
    void testSlackBodyContainsGitHubUrl() throws Exception {
        // 1. Setup Mocks
        // We mock the actual HTTP client to prevent real calls during unit testing
        OkHttpGitHubClient mockGitHubClient = mock(OkHttpGitHubClient.class);
        
        // Configure the mock to return a simulated GitHub API response (URL)
        String simulatedGitHubUrl = "https://github.com/example/bank-of-z/issues/454";
        
        // We need to mock the JSON response expected by the workflow
        // Assuming the workflow parses the JSON to extract the URL, we return a string
        // For simplicity in this red phase, we might mock the specific method the workflow uses.
        // If the workflow uses OkHttpGitHubClient directly:
        when(mockGitHubClient.createIssue(anyString(), anyString(), anyString(), anyString()))
            .thenReturn("{\"html_url\":\"" + simulatedGitHubUrl + "\"}");

        // 2. Initialize Workflow with Mocks
        DefectReportWorkflow workflow = new DefectReportWorkflow(mockGitHubClient);

        // 3. Trigger Report (Input Data from Story)
        ReportDefectCmd cmd = new ReportDefectCmd(
            "S-FB-1",
            "Fix: Validating VW-454 — GitHub URL in Slack body",
            "LOW",
            "validation",
            "21b76fa6-afb6-4593-9e1b-b5d7548ac4d1",
            Map.of("repro_steps", "1. Trigger _report_defect\n2. Verify Slack body")
        );

        // 4. Execute Workflow
        // We capture the "Slack Body" that would be sent. 
        // In the real implementation, this likely calls a SlackClient.
        // For this unit test, we verify the *content* generated by the workflow.
        String generatedSlackBody = workflow.generateSlackNotification(cmd);

        // 5. Assertions (Expected Behavior)
        assertNotNull(generatedSlackBody, "Slack body should not be null");
        assertTrue(generatedSlackBody.contains(simulatedGitHubUrl), 
            "Slack body must contain the GitHub issue URL: " + simulatedGitHubUrl + "\nActual: " + generatedSlackBody);
    }
}
