package com.example.steps;

import com.example.adapters.DefectActivitiesImpl;
import com.example.adapters.GitHubPort;
import com.example.adapters.InMemoryGitHubPort;
import com.example.adapters.SlackNotifierPort;
import com.example.adapters.SpySlackNotifier;
import com.example.domain.defect.model.ReportDefectCommand;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * S-FB-1 Regression Test: Validating VW-454 — GitHub URL in Slack body (end-to-end).
 * 
 * Scenario:
 * 1. Trigger _report_defect via temporal-worker exec (simulated via ActivityImpl call)
 * 2. Verify Slack body contains GitHub issue link
 * 
 * This test specifically validates that the Slack notification generated by the
 * defect reporting workflow includes the full URL to the created GitHub issue.
 */
class DefectReportingRegressionTest {

    private GitHubPort gitHubPort;
    private SpySlackNotifier slackNotifier;
    private DefectActivitiesImpl defectActivity;

    @BeforeEach
    void setUp() {
        // Initialize Mock Adapters
        gitHubPort = new InMemoryGitHubPort();
        slackNotifier = new SpySlackNotifier();

        // Inject into Activity Implementation
        defectActivity = new DefectActivitiesImpl(gitHubPort, slackNotifier);
    }

    @Test
    void shouldIncludeGitHubUrlInSlackBodyWhenDefectIsReported() {
        // Given: A defect report command for VForce360 PM diagnostic
        var cmd = new ReportDefectCommand(
                "21b76fa6-afb6-4593-9e1b-b5d7548ac4d1",
                "Fix: Validating VW-454",
                "Reproduction Steps: 1. Trigger report_defect...",
                ReportDefectCommand.Severity.LOW,
                "validation",
                null
        );

        // When: The defect report activity is executed
        String resultUrl = defectActivity.reportDefect(cmd);

        // Then:
        // 1. The result should be a valid GitHub URL string
        assertNotNull(resultUrl, "GitHub URL should not be null");
        assertTrue(resultUrl.startsWith("https://github.com/"), "Result should be a GitHub URL");

        // 2. The Slack notifier should have received exactly one message
        assertEquals(1, slackNotifier.getCapturedMessages().size(), "Exactly one Slack message should be sent");

        // 3. CRITICAL ASSERTION FOR S-FB-1: The Slack body must contain the GitHub link
        // Expected Behavior: Slack body includes GitHub issue: <url>
        SpySlackNotifier.Message message = slackNotifier.getCapturedMessages().get(0);
        assertTrue(
                message.message.contains(resultUrl),
                "Slack body must contain the GitHub issue link. Expected to find: " + resultUrl + " in message: " + message.message
        );

        // 4. Verify the channel is correct
        assertEquals("#vforce360-issues", message.channel, "Should post to VForce360 issues channel");
    }

    @Test
    void shouldFailIfGitHubIssueCreationFails() {
        // Given: A GitHub adapter that is configured to fail
        ((InMemoryGitHubPort) gitHubPort).setShouldFail(true);

        var cmd = new ReportDefectCommand(
                "project-id",
                "Critical Failure",
                "System down",
                ReportDefectCommand.Severity.CRITICAL,
                "core",
                null
        );

        // When/Then: Executing the report should throw an exception
        // (This ensures we don't send a Slack notification without a valid link)
        assertThrows(RuntimeException.class, () -> {
            defectActivity.reportDefect(cmd);
        });

        // And: No Slack message should have been sent
        assertTrue(slackNotifier.getCapturedMessages().isEmpty(), "No Slack message should be sent if GitHub fails");
    }
}