package com.example.steps;

import com.example.domain.validation.model.DefectAggregate;
import com.example.domain.validation.model.ReportDefectCommand;
import com.example.mocks.InMemoryDefectRepository;
import com.example.mocks.MockSlackNotificationPort;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Cucumber Steps for S-FB-1: Validating VW-454 — GitHub URL in Slack body.
 * 
 * This test class simulates the TDD Red Phase by asserting on behavior 
 * that the domain layer and port adapters must satisfy.
 */
public class SFB1Steps {

    // System Under Test components
    private final InMemoryDefectRepository repository = new InMemoryDefectRepository();
    private final MockSlackNotificationPort slackPort = new MockSlackNotificationPort();

    // State for scenario context
    private DefectAggregate defectAggregate;
    private String generatedUrl;
    private Exception capturedException;

    @Given("a defect report is triggered with title {string} and description {string}")
    public void a_defect_report_is_triggered(String title, String description) {
        // In a real temporal flow, this would be the Workflow input
        // Here we prepare the aggregate state
        this.defectAggregate = repository.createNew();
    }

    @When("the defect is processed by the domain layer")
    public void the_defect_is_processed() {
        try {
            // Simulate the processing logic
            // This command execution should produce the GitHub URL logic within the aggregate
            var events = defectAggregate.execute(new ReportDefectCommand(defectAggregate.id(), "Defect in Validation", "URL missing in Slack body"));
            
            // Apply events (In a real app, the repository handles event sourcing persistence)
            // For this unit test, we manually update state or just check the event
            if (!events.isEmpty()) {
                var event = events.get(0); // Assuming DefectReportedEvent
                // Extract URL logic - relying on the fact that the aggregate generates it
                generatedUrl = defectAggregate.getGithubUrl();
            }
        } catch (Exception e) {
            capturedException = e;
        }
    }

    @Then("the resulting Slack body should contain the GitHub issue URL")
    public void the_resulting_slack_body_should_contain_github_url() {
        // This is the core assertion for the defect fix
        assertNotNull(generatedUrl, "GitHub URL should have been generated by the aggregate");
        assertTrue(generatedUrl.startsWith("https://github.com"), "URL should point to GitHub");

        // Simulate the Slack notification activity using the mock port
        String slackBody = String.format("Issue created: %s", generatedUrl);
        slackPort.sendMessage(slackBody);

        // Assert the mock captured the URL
        assertTrue(slackPort.containsUrl(generatedUrl), "Slack message body must contain the GitHub URL");
    }

    @Then("the validation should pass")
    public void the_validation_should_pass() {
        assertNull(capturedException, "Processing should complete without exceptions");
    }
}
