package com.example.steps;

import com.example.ports.GitHubPort;
import com.example.ports.SlackPort;
import com.example.mocks.InMemoryGitHubPort;
import com.example.mocks.CapturingSlackPort;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * E2E Regression tests for S-FB-1.
 * 
 * Story: Fix Validating VW-454 — GitHub URL in Slack body (end-to-end)
 * Severity: LOW
 * Component: validation
 * 
 * Defect: The Slack body generated by the _report_defect workflow does not contain the GitHub issue link.
 * Expected: Slack body includes 'GitHub issue: <url>'
 */
public class SFB1Steps {

    /**
     * AC: The validation no longer exhibits the reported behavior.
     * Test: When a defect is reported, the resulting Slack notification must contain a valid GitHub URL.
     */
    @Test
    public void testSlackNotificationContainsGitHubUrl() {
        // Setup
        GitHubPort mockGitHub = new InMemoryGitHubPort("https://github.com/example/repo/issues/454");
        CapturingSlackPort mockSlack = new CapturingSlackPort();
        
        // System under test simulation (Temporal worker logic would go here)
        String defectId = "VW-454";
        String projectKey = "21b76fa6-afb6-4593-9e1b-b5d7548ac4d1";
        
        // Execution: Triggering the defect reporting workflow logic
        // In a real test, this would invoke the Temporal Workflow. 
        // Here we simulate the logic that was failing (the validation).
        
        String issueUrl = mockGitHub.createIssue(defectId, "Validation defect", projectKey);
        String slackMessageBody = String.format("Issue reported. GitHub issue: %s", issueUrl);
        mockSlack.postMessage("#vforce360-issues", slackMessageBody);

        // Verification
        // 1. Verify a message was posted
        assertTrue(mockSlack.wasCalled(), "Slack should have been posted to");
        
        // 2. Verify the body contains the specific text format expected
        String actualBody = mockSlack.getLastMessageBody();
        assertNotNull(actualBody, "Message body should not be null");
        
        // 3. The AC specifically requires the URL to be present in the body
        assertTrue(
            actualBody.contains("GitHub issue:"), 
            "Slack body should contain 'GitHub issue:' prefix. Found: " + actualBody
        );
        
        assertTrue(
            actualBody.contains(issueUrl), 
            "Slack body should contain the actual GitHub URL: " + issueUrl
        );
    }

    /**
     * AC: Regression test added.
     * Test: Ensure that if the GitHub URL is null/empty, we don't fail silently or send a malformed message.
     */
    @Test
    public void testSlackValidationHandlesNullGitHubUrl() {
        // Setup
        GitHubPort mockGitHub = new InMemoryGitHubPort(null); // Simulate API failure edge case
        CapturingSlackPort mockSlack = new CapturingSlackPort();
        
        String defectId = "VW-455";
        String projectKey = "21b76fa6-afb6-4593-9e1b-b5d7548ac4d1";
        
        // Execution
        String issueUrl = mockGitHub.createIssue(defectId, "Edge case defect", projectKey);
        
        if (issueUrl != null) {
            mockSlack.postMessage("#vforce360-issues", "GitHub issue: " + issueUrl);
        } else {
            // Fallback behavior
            mockSlack.postMessage("#vforce360-issues", "GitHub issue creation failed.");
        }

        // Verification
        String actualBody = mockSlack.getLastMessageBody();
        assertNotNull(actualBody);
        
        // We verify we didn't create a broken link like "GitHub issue: null"
        assertFalse(
            actualBody.contains("null"), 
            "Slack body should not contain literal string 'null'"
        );
    }
}