package com.example.steps;

import com.example.domain.defect.model.DefectAggregate;
import com.example.domain.defect.model.DefectReportedEvent;
import com.example.domain.defect.model.ReportDefectCmd;
import com.example.mocks.MockGitHubPort;
import com.example.mocks.MockSlackNotificationPort;
import com.example.ports.GitHubPort;
import com.example.ports.SlackNotificationPort;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Cucumber Steps for Story S-FB-1.
 * Validates that the Slack body contains the GitHub URL.
 */
public class SFB1Steps {

    // System Under Test (Simulating the Temporal Workflow Activity behavior)
    private DefectReportHandler handler;

    // Context
    private ReportDefectCmd command;
    private DefectReportedEvent event;
    private Exception caughtException;
    private String sentSlackMessage;

    // Mocks (managed manually or via Spring DI, shown manual for simplicity)
    private final GitHubPort gitHubPort = new MockGitHubPort();
    private final SlackNotificationPort slackPort = new MockSlackNotificationPort();

    @Given("a defect report is triggered with id {string}")
    public void a_defect_report_is_triggered(String id) {
        // Initialize handler with mocks
        this.handler = new DefectReportHandler(gitHubPort, slackPort);
        
        this.command = new ReportDefectCmd(
            id,
            "VW-454: GitHub URL missing in Slack",
            "LOW",
            "validation",
            "21b76fa6-afb6-4593-9e1b-b5d7548ac4d1",
            Map.of("reporter", "VForce360 PM")
        );
    }

    @When("the defect reporting workflow executes")
    public void the_workflow_executes() {
        try {
            // 1. Aggregate handles command
            DefectAggregate aggregate = new DefectAggregate(command.defectId());
            var events = aggregate.execute(command);
            this.event = (DefectReportedEvent) events.get(0);

            // 2. Handler (simulating Temporal Activity) processes event and notifies Slack
            // This is the integration logic we are testing end-to-end
            sentSlackMessage = handler.handle(event);
        } catch (Exception e) {
            caughtException = e;
        }
    }

    @Then("the Slack body should include the GitHub issue URL")
    public void the_slack_body_should_include_the_github_url() {
        assertNotNull(sentSlackMessage, "Slack message should not be null");
        assertFalse(sentSlackMessage.isBlank(), "Slack message should not be empty");

        // Validate Expected Behavior: "Slack body includes GitHub issue: <url>"
        // We check that the URL generated by the system is present in the message body.
        String expectedUrl = event.githubUrl();
        assertTrue(
            sentSlackMessage.contains(expectedUrl),
            "Slack body should contain the GitHub URL: " + expectedUrl + "\nActual Body: " + sentSlackMessage
        );
        
        // Additionally check for the label format expected by the user story
        assertTrue(sentSlackMessage.contains("GitHub issue"), "Message should mention GitHub issue");
    }

    @Then("the validation should not fail")
    public void the_validation_should_not_fail() {
        assertNull(caughtException, "Workflow should execute without exception. Caught: " + (caughtException != null ? caughtException.getMessage() : ""));
    }

    /**
     * Helper class representing the Application Service / Temporal Activity.
     * This class is the "implementation" under test.
     */
    private static class DefectReportHandler {
        private final GitHubPort gitHubPort;
        private final SlackNotificationPort slackPort;

        public DefectReportHandler(GitHubPort gitHubPort, SlackNotificationPort slackPort) {
            this.gitHubPort = gitHubPort;
            this.slackPort = slackPort;
        }

        public String handle(DefectReportedEvent event) {
            // Validate GitHub URL existence via Port
            String url = gitHubPort.getIssueUrl(event.title(), event.projectId());
            if (url == null || url.isBlank()) {
                throw new IllegalStateException("Failed to retrieve GitHub URL for defect: " + event.aggregateId());
            }

            // Construct Slack Message
            String message = String.format(
                "Defect Reported: %s%nSeverity: %s%nGitHub issue: <%s|%s>",
                event.title(), event.severity(), url, url
            );

            // Send via Port
            slackPort.sendNotification(message);
            return message;
        }
    }
}