package com.example.steps;

import com.example.domain.vforce360.model.ReportDefectCommand;
import com.example.domain.vforce360.model.SlackNotification;
import com.example.domain.vforce360.ports.ReportDefectPort;
import com.example.mocks.MockReportDefectAdapter;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.When;
import io.cucumber.java.en.Then;
import org.junit.jupiter.api.Assertions;

import java.util.Map;

/**
 * BDD Steps for validating VW-454.
 * Ensures that the Slack body generated by the defect reporting workflow
 * contains the GitHub issue URL.
 */
public class VW454Steps {

    private ReportDefectPort adapter;
    private ReportDefectCommand command;
    private SlackNotification result;

    // Using the mock adapter directly to simulate the temporal-worker exec
    public VW454Steps() {
        this.adapter = new MockReportDefectAdapter();
    }

    @Given("a defect report trigger is received")
    public void a_defect_report_trigger_is_received() {
        command = new ReportDefectCommand(
                "VW-454: GitHub URL in Slack body",
                "Validating VW-454",
                "LOW",
                "validation",
                "21b76fa6-afb6-4593-9e1b-b5d7548ac4d1",
                Map.of("storyId", "S-FB-1")
        );
    }

    @When("the temporal-worker executes _report_defect")
    public void the_temporal_worker_executes_report_defect() {
        result = adapter.reportDefect(command);
    }

    @Then("the Slack body contains the GitHub issue link")
    public void the_slack_body_contains_the_github_issue_link() {
        Assertions.assertNotNull(result, "SlackNotification should not be null");
        Assertions.assertNotNull(result.body(), "Slack body should not be null");

        // The core assertion for VW-454
        // Checks that the body contains the GitHub URL format
        Assertions.assertTrue(
                result.body().contains("github.com"),
                "Slack body should contain 'github.com'"
        );

        Assertions.assertTrue(
                result.body().contains("GitHub Issue:"),
                "Slack body should contain the label 'GitHub Issue:'"
        );

        // Validate structure roughly matches <url> expectation
        String[] parts = result.body().split("GitHub Issue:");
        Assertions.assertTrue(
                parts.length > 1,
                "Slack body should contain content after 'GitHub Issue:'"
        );
        String urlPart = parts[1].trim();
        Assertions.assertTrue(
                urlPart.startsWith("http"),
                "The URL should start with http/https"
        );
    }
}