package com.example.steps;

import com.example.domain.shared.DomainEvent;
import com.example.domain.vforce360.model.DefectAggregate;
import com.example.domain.vforce360.model.DefectReportedEvent;
import com.example.domain.vforce360.model.ReportDefectCmd;
import com.example.mocks.MockGitHubIssuePort;
import com.example.mocks.MockSlackNotificationPort;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.When;
import io.cucumber.java.en.Then;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Cucumber Steps for validating VW-454.
 * Ensures that when a defect is reported via Temporal, the resulting context
 * includes a valid GitHub URL for the Slack body.
 */
public class VW454Steps {

    // The Aggregate Under Test
    private DefectAggregate defectAggregate;

    // Mocks for External Dependencies
    private final MockGitHubIssuePort gitHubPort = new MockGitHubIssuePort();
    private final MockSlackNotificationPort slackPort = new MockSlackNotificationPort();

    // State for verification
    private List<DomainEvent> resultEvents;
    private Exception capturedException;

    @Given("a defect report is generated by VForce360")
    public void a_defect_report_is_generated_by_vforce360() {
        // Setup aggregate
        defectAggregate = new DefectAggregate("VW-454");
    }

    @When("the temporal worker executes _report_defect")
    public void the_temporal_worker_executes_report_defect() {
        // Simulating the command that Temporal Workflow would trigger
        ReportDefectCmd cmd = new ReportDefectCmd(
                "VW-454",
                "Fix: Validating VW-454 — GitHub URL in Slack body",
                "Defect reported by user.",
                ReportDefectCmd.Severity.LOW,
                Map.of("component", "validation", "project", "21b76fa6")
        );

        // Execute Command (Red Phase: Implementation is empty/placeholder)
        try {
            resultEvents = defectAggregate.execute(cmd);
        } catch (Exception e) {
            capturedException = e;
        }

        // Simulate the Saga/Process Manager side-effect using Mocks
        if (resultEvents != null && !resultEvents.isEmpty()) {
            DomainEvent event = resultEvents.get(0);
            if (event instanceof DefectReportedEvent de) {
                // Create GitHub Issue (Mock)
                String url = gitHubPort.createIssue(de.title(), de.description());

                // Construct Slack Body
                // This mimics the logic we want to verify: The body MUST contain the URL
                String slackBody = String.format(
                        "New Defect Reported: %s\nSeverity: %s\nGitHub Issue: %s",
                        de.title(), de.severity(), url
                );

                slackPort.sendMessage("#vforce360-issues", slackBody);
            }
        }
    }

    @Then("the Slack body should contain the GitHub issue URL")
    public void the_slack_body_should_contain_the_github_issue_url() {
        // If the aggregate failed to execute, fail the test immediately (TDD Red)
        if (capturedException != null) {
            fail("Aggregate execution failed: " + capturedException.getMessage());
        }

        // Verify the event was produced
        assertFalse(resultEvents.isEmpty(), "Expected at least one domain event");
        assertTrue(resultEvents.get(0) instanceof DefectReportedEvent, "Expected DefectReportedEvent");

        // Verify the Mock Slack Port received the message
        // Note: We rely on the mock to prove the 'system' (under test) behaved correctly.
        boolean found = slackPort.receivedMessageContaining("https://github.com");
        assertTrue(found, "Expected Slack body to include GitHub issue URL, but it was not found in the mock.");

        // Explicit check for the format expected in the defect report
        boolean foundKeyword = slackPort.receivedMessageContaining("GitHub Issue:");
        assertTrue(foundKeyword, "Expected Slack body to explicitly state 'GitHub Issue:'");
    }
}