package com.example.workflow;

import com.example.ports.GitHubPort;
import com.example.ports.SlackPort;
import io.temporal.workflow.Workflow;

/**
 * Implementation of the Defect Reporting Workflow.
 * Fixes VW-454 by ensuring the GitHub URL is passed to the Slack activity.
 */
public class ReportDefectWorkflowImpl implements ReportDefectWorkflow {

    // Activity interfaces (Stubs generated by Temporal)
    private final DefectActivities activities;

    public ReportDefectWorkflowImpl() {
        // Temporal generates the implementation of the Activities interface at runtime.
        this.activities = Workflow.newActivityStub(DefectActivities.class);
    }

    @Override
    public void reportDefect(String defectTitle, String defectBody) {
        // Step 1: Create GitHub Issue
        String githubUrl = activities.createGitHubIssue(defectTitle, defectBody);

        // Step 2: Notify Slack with the URL
        // Per VW-454, the body must explicitly contain the GitHub URL.
        activities.notifySlack(defectTitle, githubUrl);
    }
}
