package com.example.workflow;

import com.example.application.DefectReportCommand;
import com.example.application.DefectReportingActivity;
import io.temporal.workflow.Workflow;

/**
 * Workflow implementation for defect reporting.
 * Orchestrates the call to the Activity.
 */
public class ReportDefectWorkflowImpl implements ReportDefectWorkflow {

    // Activities stub is generated by Temporal at runtime
    private final DefectReportingActivity activities = Workflow.newActivityStub(DefectReportingActivity.class);

    @Override
    public String reportDefect(DefectReportCommand command) {
        // Simply delegate to the activity logic
        return activities.execute(command);
    }
}
