# Spring Boot App Configuration
spring.application.name=bank-of-z

# Integration Switches (Set to true in production, false for tests)
integration.slack.enabled=false
integration.github.enabled=false

# GitHub Properties (used by the real adapter)
integration.github.owner=fake-org
integration.github.repo=bank-of-z
