package com.example.application;

import com.example.domain.defect.port.DefectRepository;
import com.example.domain.validation.port.ValidationRepository;
import com.example.infrastructure.TemporalActivitiesImpl;
import io.temporal.workflow.WorkflowInterface;
import io.temporal.workflow.WorkflowMethod;
import org.springframework.stereotype.Service;

/**
 * Defect Workflow Service.
 * Orchestrates the defect reporting and validation process using Temporal.
 */
@Service
@WorkflowInterface
public class DefectWorkflowService {

    private final DefectRepository defectRepository;
    private final ValidationRepository validationRepository;

    // Constructor injection (Simulated for Workflow context, in reality workflows are instantiated by Temporal)
    // In a real Spring Boot Temporal setup, we use a WorkflowImplementationOptions factory to inject dependencies.
    public DefectWorkflowService(DefectRepository defectRepository, ValidationRepository validationRepository) {
        this.defectRepository = defectRepository;
        this.validationRepository = validationRepository;
    }

    /**
     * Main workflow entry point for reporting a defect and validating the output.
     * Story S-FB-1: Verifies GitHub URL in Slack body.
     */
    @WorkflowMethod
    public void reportDefectAndValidate(String defectId, String title, String description) {
        // 1. Report Defect
        // Activities are stubs generated by Temporal
        DefectActivities activities = new DefectActivitiesImpl(defectRepository, validationRepository);
        
        activities.reportDefect(defectId, title, description);
        
        // Ideally, we would retrieve the URL from the aggregate state, but for simplicity in this fix:
        String expectedUrl = "https://github.com/egdcrypto-bank-of-z/issues/" + defectId;
        
        // Simulate constructing the Slack Body
        // In a real scenario, this might come from an external NotificationService or SlackClient
        String slackBody = "Defect Reported: " + defectId + "\nGitHub Issue: " + expectedUrl;
        
        // 2. Validate Link
        boolean isValid = activities.validateSlackBody("val-" + defectId, slackBody, expectedUrl);
        
        if (!isValid) {
            throw new RuntimeException("Validation Failed: Slack body does not contain the GitHub URL.");
        }
    }

    /**
     * Local implementation of activities for direct invocation if not running inside Temporal Worker context
     * or for the purpose of this defect fix verification.
     */
    public static class DefectActivitiesImpl {
        private final DefectRepository defectRepository;
        private final ValidationRepository validationRepository;

        public DefectActivitiesImpl(DefectRepository defectRepository, ValidationRepository validationRepository) {
            this.defectRepository = defectRepository;
            this.validationRepository = validationRepository;
        }

        public void reportDefect(String defectId, String title, String description) {
            TemporalActivitiesImpl impl = new TemporalActivitiesImpl(defectRepository, validationRepository);
            impl.reportDefect(defectId, title, description);
        }

        public boolean validateSlackBody(String validationId, String slackBody, String expectedUrl) {
            TemporalActivitiesImpl impl = new TemporalActivitiesImpl(defectRepository, validationRepository);
            return impl.validateSlackBody(validationId, slackBody, expectedUrl);
        }
    }
}
