{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teller.backend.secretName" . }}
  labels:
    {{- include "teller.labels" (dict "ctx" . "component" .Values.backend.name) | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.backend.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
