{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teller.fullname" . }}-{{ .Values.frontend.name }}
  labels:
    {{- include "teller.labels" (dict "ctx" . "component" .Values.frontend.name) | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "teller.selectorLabels" (dict "ctx" . "component" .Values.frontend.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "teller.labels" (dict "ctx" . "component" .Values.frontend.name) | nindent 8 }}
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ include "teller.image" (dict "global" .Values.global "image" .Values.frontend.image) }}
          imagePullPolicy: {{ include "teller.pullPolicy" (dict "global" .Values.global "image" .Values.frontend.image) }}
          securityContext:
            {{- toYaml .Values.frontend.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}
