{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teller.fullname" . }}-{{ .Values.frontend.name }}
  labels:
    {{- include "teller.labels" (dict "ctx" . "component" .Values.frontend.name) | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "teller.selectorLabels" (dict "ctx" . "component" .Values.frontend.name) | nindent 4 }}
{{- end }}
