package com.example.domain.validation;

import com.example.domain.defect.mocks.MockSlackNotificationPort;
import com.example.domain.defect.ports.SlackNotificationPort;
import com.example.domain.defect.model.ReportDefectCommand;
import com.example.domain.defect.service.DefectReportingService;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * TDD Red Phase: Regression test for VW-454.
 * Validates that the Slack notification body generated by the Temporal workflow
 * includes the GitHub issue URL when reporting a defect.
 */
class VW454RegressionTest {

    @Test
    void shouldContainGitHubIssueUrlInSlackBodyWhenDefectReported() {
        // Given
        // We expect the system to interact with an external Slack API.
        // We mock this interaction to verify the payload content without real I/O.
        MockSlackNotificationPort mockSlack = new MockSlackNotificationPort();
        DefectReportingService service = new DefectReportingService(mockSlack);

        String expectedProjectId = "21b76fa6-afb6-4593-9e1b-b5d7548ac4d1";
        String expectedTitle = "VW-454: GitHub URL Validation";
        String expectedGithubUrl = "https://github.com/mock-repo/issues/454";

        ReportDefectCommand cmd = new ReportDefectCommand(
            expectedProjectId,
            expectedTitle,
            "Defect in validation",
            expectedGithubUrl
        );

        // When
        // The Temporal workflow (simulated here by the service) executes the notification logic.
        service.reportDefect(cmd);

        // Then
        // Verify that the mock port received a payload containing the GitHub URL.
        // This acts as the regression check ensuring the URL is present in the body.
        assertTrue(
            mockSlack.getLastBody().contains("<" + expectedGithubUrl + ">"),
            "Slack body must contain formatted GitHub URL"
        );
    }
}
