package com.example.domain.defect;

import com.example.domain.defect.model.ReportDefectCmd;
import com.example.domain.shared.UnknownCommandException;
import com.example.mocks.MockGitHubIssuePort;
import com.example.mocks.MockSlackNotificationPort;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit Tests for Defect Aggregate.
 * Validates the domain logic for reporting defects and ensuring proper event generation.
 */
public class DefectAggregateTest {

    private MockGitHubIssuePort mockGitHub;
    private MockSlackNotificationPort mockSlack;
    private DefectAggregate aggregate;
    private static final String SLACK_CHANNEL_ID = "C-FAKE123";

    @BeforeEach
    void setUp() {
        mockGitHub = new MockGitHubIssuePort();
        mockSlack = new MockSlackNotificationPort();
        aggregate = new DefectAggregate("VW-454", mockGitHub, mockSlack, SLACK_CHANNEL_ID);
    }

    @Test
    void testExecuteReportDefectSuccess() {
        // Given
        ReportDefectCmd cmd = new ReportDefectCmd(
            "VW-454",
            "GitHub URL missing in Slack body",
            "The defect report fails to include the link in the notification.",
            "LOW",
            "validation"
        );

        // Expected GitHub URL generated by mock
        String expectedUrl = "https://github.com/fake-org/project/issues/" + cmd.title().hashCode();

        // When
        var events = aggregate.execute(cmd);

        // Then
        assertFalse(events.isEmpty(), "Should generate a DefectReportedEvent");
        assertEquals(1, events.size());

        // Verify State Change
        assertEquals(1, aggregate.getVersion());

        // Verify External Side Effects (via Mocks)
        assertEquals(expectedUrl, mockGitHub.getLastCreatedIssueUrl());
        assertTrue(mockSlack.lastMessageContainsUrl(SLACK_CHANNEL_ID, expectedUrl),
            "Slack body must contain the GitHub Issue URL");

        // Verify Event Content
        var event = events.get(0);
        assertEquals("VW-454", event.aggregateId());
        assertEquals("DefectReported", event.type());
        assertEquals(expectedUrl, event.githubIssueUrl());
    }

    @Test
    void testRejectsInvalidCommand() {
        // Given
        String invalidCmd = "Not a defect command";

        // When & Then
        assertThrows(UnknownCommandException.class, () -> aggregate.execute(invalidCmd));
    }

    @Test
    void testRejectsBlankDefectId() {
        // Given
        ReportDefectCmd cmd = new ReportDefectCmd("", "Title", "Desc", "HIGH", "core");

        // When & Then
        assertThrows(IllegalArgumentException.class, () -> aggregate.execute(cmd));
    }
}
