#!/usr/bin/env bash
# BANK S-42 — Regenerate the ArgoCD Application manifests from the Helm chart.
#
# Reads:
#   * deploy/helm/teller/Chart.yaml             (name, repo URL via maintainers)
#   * deploy/helm/teller/values.yaml            (defaults)
#   * deploy/helm/teller/values-microk8s.yaml   (staging overlay)
#   * deploy/helm/teller/values-eks.yaml        (production overlay)
#
# Writes:
#   * deploy/argocd/application-staging.yaml
#   * deploy/argocd/application-production.yaml
#
# Re-running the script must produce a byte-identical result to what is in
# Git. `ci.yml` enforces this on every PR via `git diff --exit-code` so a
# chart change always lands together with its corresponding ArgoCD update.
#
# Usage:
#   ./deploy/argocd/generate.sh           # write files
#   ./deploy/argocd/generate.sh --check   # exit 1 if generated != on-disk
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CHART_DIR="${REPO_ROOT}/deploy/helm/teller"
OUT_DIR="${REPO_ROOT}/deploy/argocd"
MODE="${1:-write}"

CHART_NAME="$(awk '/^name:/ {print $2; exit}' "${CHART_DIR}/Chart.yaml")"
REPO_URL="$(awk '/^[[:space:]]*url:/ {gsub(/^[[:space:]]+url:[[:space:]]+/,""); print; exit}' "${CHART_DIR}/Chart.yaml")"

if [[ -z "${CHART_NAME}" || -z "${REPO_URL}" ]]; then
  echo "generate.sh: failed to read chart metadata" >&2
  exit 2
fi

# Render one Application YAML from the chart + the given env overlay.
render_application() {
  local env="$1"           # staging | production
  local overlay="$2"       # values-microk8s.yaml | values-eks.yaml
  local cluster="$3"       # ArgoCD destination cluster name
  local namespace="$4"     # target namespace
  local sync_mode="$5"     # automated | manual
  local history="$6"       # revisionHistoryLimit
  local retry_dur="$7"     # initial retry backoff
  local retry_max="$8"     # max retry backoff
  local retry_limit="$9"

  local automated_block=""
  local notify_lines=""
  if [[ "${sync_mode}" == "automated" ]]; then
    automated_block=$'    automated:\n      prune: true\n      selfHeal: true\n      allowEmpty: false\n'
    notify_lines=$'    notifications.argoproj.io/subscribe.on-sync-failed.slack: bank-deploys\n    notifications.argoproj.io/subscribe.on-health-degraded.slack: bank-deploys'
  else
    notify_lines=$'    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: bank-deploys\n    notifications.argoproj.io/subscribe.on-sync-failed.slack: bank-deploys\n    notifications.argoproj.io/subscribe.on-health-degraded.slack: bank-deploys\n    notifications.argoproj.io/subscribe.on-deployed.slack: bank-deploys'
  fi

  cat <<YAML
# GENERATED by deploy/argocd/generate.sh from deploy/helm/${CHART_NAME}/${overlay}.
# DO NOT EDIT BY HAND — re-run \`deploy/argocd/generate.sh\` after chart changes.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${CHART_NAME}-${env}
  namespace: argocd
  labels:
    app.kubernetes.io/name: ${CHART_NAME}
    app.kubernetes.io/part-of: bank-of-z
    bank.example.com/environment: ${env}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
${notify_lines}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bank-of-z
  source:
    repoURL: ${REPO_URL}
    targetRevision: main
    path: deploy/helm/${CHART_NAME}
    helm:
      releaseName: ${CHART_NAME}
      valueFiles:
        - values.yaml
        - ${overlay}
  destination:
    name: ${cluster}
    namespace: ${namespace}
  syncPolicy:
${automated_block}    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: ${retry_limit}
      backoff:
        duration: ${retry_dur}
        factor: 2
        maxDuration: ${retry_max}
  revisionHistoryLimit: ${history}
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
YAML
}

generate() {
  # Staging: automated sync, shorter retry, smaller history.
  render_application staging    values-microk8s.yaml microk8s-staging  bank-staging    automated 20 30s 5m  5 \
    > "${OUT_DIR}/.application-staging.yaml.new"
  # Production: manual sync gate, slower retry, deeper history (a sprint of rollbacks).
  render_application production values-eks.yaml      eks-production    bank-production manual    50 1m  10m 3 \
    > "${OUT_DIR}/.application-production.yaml.new"
}

case "${MODE}" in
  --check)
    generate
    fail=0
    for f in application-staging application-production; do
      if ! diff -u "${OUT_DIR}/${f}.yaml" "${OUT_DIR}/.${f}.yaml.new" >/dev/null 2>&1; then
        echo "generate.sh: ${f}.yaml is out of sync with the chart." >&2
        diff -u "${OUT_DIR}/${f}.yaml" "${OUT_DIR}/.${f}.yaml.new" || true
        fail=1
      fi
    done
    rm -f "${OUT_DIR}/.application-staging.yaml.new" \
          "${OUT_DIR}/.application-production.yaml.new"
    exit "${fail}"
    ;;
  write|*)
    generate
    mv "${OUT_DIR}/.application-staging.yaml.new"    "${OUT_DIR}/application-staging.yaml"
    mv "${OUT_DIR}/.application-production.yaml.new" "${OUT_DIR}/application-production.yaml"
    echo "generate.sh: regenerated application-{staging,production}.yaml"
    ;;
esac
