package com.example.domain.support;

import com.example.ports.SlackClient;
import com.example.ports.GitHubClient;
import com.example.mocks.MockSlackClient;
import com.example.mocks.MockGitHubClient;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.net.URI;
import java.util.Map;

/**
 * Test Suite for S-FB-1: Validating VW-454 — GitHub URL in Slack body (end-to-end)
 *
 * Context: VForce360 PM diagnostic conversation identified a defect where the Slack
 * notification body does not contain the expected GitHub issue link.
 *
 * This suite covers the regression scenario by mocking external dependencies (Slack, GitHub)
 * and verifying the content passed to the Slack client contains the correct URL.
 */
public class SlackNotificationServiceTest {

    private MockSlackClient mockSlackClient;
    private MockGitHubClient mockGitHubClient;
    private SlackNotificationService service;

    @BeforeEach
    public void setUp() {
        // Instantiate Mock Adapters
        mockSlackClient = new MockSlackClient();
        mockGitHubClient = new MockGitHubClient();

        // Inject mocks into the service under test
        // In Spring Boot, this would be handled by @MockBean, but here we do manual injection for clarity
        service = new SlackNotificationService(mockSlackClient, mockGitHubClient);
    }

    /**
     * Test Case: Verify Slack body contains GitHub issue URL
     *
     * Given: A defect report command is triggered via temporal-worker exec
     * When: The notification process is executed
     * Then: The Slack body must include the valid GitHub issue URL
     */
    @Test
    public void testReportDefect_ShouldIncludeGitHubUrlInSlackBody() {
        // Arrange
        String expectedTitle = "VW-454: Validation Error";
        String expectedDescription = "Critical validation failure in transaction module.";
        String expectedGitUrl = "https://github.com/project-repo/issues/454";

        // Configure Mock GitHub Adapter to return a valid URL
        mockGitHubClient.setMockIssueUrl(expectedGitUrl);

        // Act
        service.reportDefect(expectedTitle, expectedDescription, "VW-454");

        // Assert - Verify Interaction with Mock Slack Adapter
        // We verify that the message sent to Slack contains the link generated by GitHub
        Map<String, Object> payloadSentToSlack = mockSlackClient.getCapturedPayload();
        
        assertNotNull(payloadSentToSlack, "Slack payload should not be null");
        
        // Extract body for assertion (mimicking the structure of a Slack message)
        String actualBody = (String) payloadSentToSlack.get("text");

        assertTrue(actualBody.contains(expectedGitUrl), 
            "Slack body should contain the GitHub issue URL. Expected: " + expectedGitUrl + " in body: " + actualBody);
        
        // Regression check: ensure it's not just the tag, but the full URL
        assertTrue(actualBody.startsWith("http"), "URL should be a valid http link");
    }

    /**
     * Test Case: Verify validation fails if GitHub URL is missing
     *
     * Given: A defect report command is triggered
     * And: The GitHub service fails to generate a URL (returns null/empty)
     * When: The notification process is executed
     * Then: The service should throw an IllegalStateException preventing invalid Slack posts
     */
    @Test
    public void testReportDefect_ShouldThrowException_WhenGitHubUrlIsMissing() {
        // Arrange
        // Configure Mock GitHub Adapter to return null/empty (simulating a failure)
        mockGitHubClient.setMockIssueUrl(null);

        // Act & Assert
        IllegalStateException exception = assertThrows(IllegalStateException.class, () -> {
            service.reportDefect("Title", "Desc", "VW-454");
        });

        assertTrue(exception.getMessage().contains("GitHub URL"), 
            "Exception message should indicate the missing GitHub URL");
        
        // Ensure nothing was sent to Slack in this failure scenario
        assertNull(mockSlackClient.getCapturedPayload(), "No message should be sent to Slack if GitHub URL generation fails");
    }
}
