package com.example.workflows;

import io.temporal.workflow.Workflow;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Workflow implementation for S-FB-1.
 * Orchestrates GitHub issue creation and Slack notification.
 * S-FB-1: Ensure Slack body contains GitHub URL.
 */
public class ReportDefectWorkflowImpl implements ReportDefectWorkflow {

    private static final Logger log = LoggerFactory.getLogger(ReportDefectWorkflowImpl.class);

    // Activity stubs are generated by Temporal at runtime
    private final ReportDefectActivity activities = Workflow.newActivityStub(ReportDefectActivity.class);

    @Override
    public void reportDefect(String title, String description, String component) {
        log.info("Starting defect reporting for: {}", title);

        // Step 1: Create GitHub Issue
        String githubUrl = activities.createGitHubIssue(title, description, component);
        
        log.info("GitHub issue created: {}", githubUrl);

        // Step 2: Prepare and Send Slack Notification
        // S-FB-1 Requirement: The body MUST include the GitHub URL
        String slackBody = String.format("Defect Reported: %s\nGitHub Issue: %s", title, githubUrl);
        String channel = "#vforce360-issues";

        activities.sendSlackNotification(channel, slackBody);

        log.info("Slack notification sent to {} with URL link.", channel);
    }
}
