package com.example.workflows;

import com.example.application.DefectReportingActivity;
import io.temporal.spring.boot.WorkflowImpl;
import io.temporal.workflow.Workflow;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.Duration;

/**
 * Implementation of the Defect Reporting Workflow.
 * Orchestrates calls to the Activity layer.
 */
@WorkflowImpl(taskQueue = "DEFECT_REPORTING_TASK_QUEUE")
public class ReportDefectWorkflowImpl implements ReportDefectWorkflow {

    private static final Logger log = LoggerFactory.getLogger(ReportDefectWorkflowImpl.class);

    // Activity stubs are generated by Temporal at runtime.
    // Note: TestEnvironment allows us to register mock implementations for this stub.
    private final DefectReportingActivity activity = Workflow.newActivityStub(
            DefectReportingActivity.class,
            io.temporal.activity.ActivityOptions.newBuilder()
                    .setScheduleToCloseTimeout(Duration.ofSeconds(10))
                    .build()
    );

    @Override
    public String reportDefect(String defectTitle, String defectBody) {
        log.info("Starting defect reporting for: {}", defectTitle);

        // 1. Create GitHub Issue
        String githubUrl = activity.createGitHubIssue(defectTitle, defectBody);
        log.info("Created GitHub Issue: {}", githubUrl);

        // 2. Notify Slack
        // Requirement: Slack body must include the GitHub issue URL.
        String slackBody = "Defect Reported: " + defectTitle + "\n" +
                           "GitHub Issue: " + githubUrl;

        activity.postToSlack("#vforce360-issues", slackBody);

        return githubUrl;
    }
}