Feature: VForce360 Defect Reporting Integration (VW-454)

  Scenario: Validating GitHub URL in Slack body during defect reporting
    Given a defect report is generated by VForce360
    When the temporal worker executes _report_defect
    Then the Slack body should contain the GitHub issue URL
