Feature: Validating VW-454 — GitHub URL in Slack body (end-to-end)

  As a VForce360 Engineer
  I want defect reports generated by the Temporal worker to include the GitHub Issue URL in the Slack body
  So that operators can quickly navigate to the issue without searching logs

  Scenario: Triggering _report_defect includes GitHub URL in Slack notification
    Given the Temporal worker is ready to report a defect
    When _report_defect is triggered with a GitHub issue link "https://github.com/bank-of-z/repos/issues/454"
    Then the Slack body should contain the GitHub issue URL "https://github.com/bank-of-z/repos/issues/454"
    And the Slack message should be posted to channel "#vforce360-issues"
