package com.example.e2e.regression;

import com.example.adapters.secondary.SlackNotifierPort;
import com.example.domain.shared.Command;
import com.example.mocks.InMemoryReconciliationBatchRepository;
import com.example.ports.secondary.ReportDefectPort;
import com.example.service.ReportDefectService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

import java.util.concurrent.CompletableFuture;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * Regression Test for Story S-FB-1.
 * Validates that the Slack body generated by _report_defect contains the GitHub issue URL.
 */
public class S_FB_1_SlackUrlValidationTest {

    private ReportDefectPort reportDefectPort;
    private SlackNotifierPort mockSlackNotifier;
    private InMemoryReconciliationBatchRepository repo;

    @BeforeEach
    void setUp() {
        mockSlackNotifier = mock(SlackNotifierPort.class);
        // Assume async success for the mock unless specified otherwise
        when(mockSlackNotifier.sendNotification(anyString())).thenReturn(CompletableFuture.completedFuture("ok"));
        
        repo = new InMemoryReconciliationBatchRepository();
        reportDefectPort = new ReportDefectService(mockSlackNotifier, repo);
    }

    @Test
    void testReportDefect_ShouldContainGitHubUrlInSlackBody() {
        // Arrange
        String expectedTitle = "VW-454 Validation Failure";
        String expectedUrl = "https://github.com/bank-of-z/issues/454";
        String defectMessage = "Slack body contains GitHub issue link";

        // We need to verify the interaction with the Slack port
        ArgumentCaptor<String> payloadCaptor = ArgumentCaptor.forClass(String.class);

        // Act
        // Assuming a simple synchronous wrapper or blocking for the test
        reportDefectPort.reportDefect(expectedTitle, expectedUrl, defectMessage);
        
        // Assert
        verify(mockSlackNotifier).sendNotification(payloadCaptor.capture());
        String actualPayload = payloadCaptor.getValue();

        // Verify the URL is present in the body
        assertTrue(actualPayload.contains(expectedUrl), 
            "Slack body should contain the GitHub issue URL: " + expectedUrl);
        
        // Verify it's not just empty
        assertFalse(actualPayload.isBlank(), "Slack body should not be blank");
    }
}
