package com.example.vforce.adapter;

/**
 * Port interface for executing Temporal activities.
 * Implemented by the real Temporal worker and mocked for tests.
 */
public interface TemporalActivityPort {
    /**
     * Simulates the execution of the '_report_defect' workflow/activity.
     * @return The formatted body of the Slack message generated by the workflow.
     */
    String executeReportDefect();
}
