package com.example.defect;

import io.temporal.workflow.Workflow;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Implementation of the {@link DefectReportWorkflow}.
 * This is the entry point for the Temporal execution.
 */
public class DefectReportWorkflowImpl implements DefectReportWorkflow {

    private static final Logger log = LoggerFactory.getLogger(DefectReportWorkflowImpl.class);

    // Activity stubs are generated by Temporal at runtime
    private final DefectReportActivity activity = Workflow.newActivityStub(DefectReportActivity.class);

    @Override
    public void reportDefect(String title, String description, String slackChannel) {
        log.info("Starting defect report workflow for: {}", title);
        activity.reportDefect(title, description, slackChannel);
    }
}
